apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-agent
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: workflow-agent
        dapr.io/app-port: "8004"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "59213"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: workflow-agent
    spec:
      containers:
      - env:
        - name: APP_PORT
          value: "8004"
        - name: DAPR_METRICS_PORT
          value: "59213"
        - name: DEBUG
          value: "true"
        - name: APP_ID
          value: workflow-agent
        - name: APP_CHANNEL_ADDRESS
        envFrom:
        - secretRef:
            name: openai-secrets
        image: localhost:5001/workflow-agent:latest
        imagePullPolicy: Always
        name: workflow-agent
        ports:
        - containerPort: 8004
        resources: {}
