apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-agent
  name: workflow-agent
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8004
  selector:
    app: workflow-agent
  type: ClusterIP
